---
protocol-key-pair:
  path: /home/user/kehliu-cs496/sui-genesis/4_validator/key-pairs/v2_protocol.key
worker-key-pair:
  path: /home/user/kehliu-cs496/sui-genesis/4_validator/key-pairs/v2_worker.key
network-key-pair:
  path: /home/user/kehliu-cs496/sui-genesis/4_validator/key-pairs/v2_network.key
account-key-pair:
  path: /home/user/kehliu-cs496/sui-genesis/4_validator/key-pairs/v2_account.key
db-path: /home/user/kehliu-cs496/sui-genesis/4_validator/db/v2/authorities_db
network-address: /ip4/0.0.0.0/tcp/9090/http
metrics-address: 0.0.0.0:9196
admin-interface-port: 1340
consensus-config:
  address: /ip4/127.0.0.1/tcp/9093/http
  db-path: /home/user/kehliu-cs496/sui-genesis/4_validator/db/v2/consensus_db
  internal-worker-address: null
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 1000ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/33293/http
    network_admin_server:
      primary_network_admin_server_port: 41305
      worker_network_admin_server_base_port: 41671
enable-event-processing: false
p2p-config:
  listen-address: 127.0.0.1:9094
  external-address: /ip4/127.0.0.1/udp/9094 # UPDATE THIS
  anemo-config:
    max-concurrent-connections: 0
  seed-peers:
    - peer-id: fd2ad62d28ec130a7ed577f10a973db87f0eb8cf423fec739021dd3d44475880 
      address: /ip4/127.0.0.1/udp/8094
    - peer-id: 748e7dcd51dac24385246f465db03f45a0a2e3c141fb674acdb9c7f0fdec9c8a 
      address: /ip4/127.0.0.1/udp/9084
    - peer-id: 9f9039f776d020f321b0199a678012e1e1b8f4459e968ef2a87b8a7fccff822d
      address: /ip4/127.0.0.1/udp/9094
    - peer-id: a067b665f828d958a90245ae23d164cec2afe1b5152f6f5a0014fd8afc80cdbb 
      address: /ip4/127.0.0.1/udp/9584
    - peer-id: 5516a701da3930f53640995ab400772cd34ab6108032e38330d33557a7e460cb
      address: /ip4/127.0.0.1/udp/8084
    - peer-id: 977c3037ef2ac939f105567c26d46f354628ffad5a4c42fb9f1101083b2952dc
      address: /ip4/127.0.0.1/udp/8884
    - peer-id: 820e65c926b01b59166359140425ba85945ed646937fe62d6785a4c9cbb40e8c
      address: /ip4/127.0.0.1/udp/8894  
genesis:
  genesis-file-location: /home/user/kehliu-cs496/sui-genesis/4_validator/genesis.blob
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 5
  max-transactions-in-batch: 1000
end-of-epoch-broadcast-channel-capacity: 128
checkpoint-executor-config:
  checkpoint-execution-max-concurrency: 200
  local-execution-timeout-sec: 10
db-checkpoint-config:
  perform-db-checkpoints-at-epoch-end: false
indirect-objects-threshold: 18446744073709551615
metrics:
  push-interval-seconds: 60
  # push-url: https://metrics-proxy.testnet.sui.io:8443/publish/metrics
  # push-url: https://metrics-proxy.mainnet.sui.io:8443/publish/metrics
